# Use DecapBridge PKCE auth (required)
backend:
  name: git-gateway
  repo: rgb-monster/rgb.monster
  branch: main
  auth_type: pkce
  base_url: https://auth.decapbridge.com
  auth_endpoint: /sites/b57b2658-a8fd-45eb-a36e-66e7ca07ab8b/pkce
  auth_token_endpoint: /sites/b57b2658-a8fd-45eb-a36e-66e7ca07ab8b/token
  gateway_url: https://gateway.decapbridge.com

  # See who did what (optional)
  commit_messages:
    create: Create {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    update: Update {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    delete: Delete {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    uploadMedia: Upload “{{path}}” - {{author-name}} <{{author-login}}> via DecapBridge
    deleteMedia: Delete “{{path}}” - {{author-name}} <{{author-login}}> via DecapBridge
    openAuthoring: Message {{message}} - {{author-name}} <{{author-login}}> via DecapBridge

# Enable PKCE fields (optional, recommended)
auth:
  email_claim: email
  first_name_claim: first_name
  last_name_claim: last_name
  avatar_url_claim: avatar_url

# Better Decap + Bridge logo (optional)
logo_url: https://decapbridge.com/decapcms-with-bridge.svg

# Add site links in Decap CMS (optional)
site_url: https://rgb.monster

local_backend: true

media_folder: "public"
public_folder: "/"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "index.md"
        label: "Home"
        name: "home"
        fields:
          - {label: "Home", name: "home", widget: "boolean", default: true}
          - {label: "Footer", name: "footer", widget: "select", options: ["light", "dark"], default: "light"}
          - {label: "Layout", name: "layout", widget: "string", default: "wide"}
          - {label: "Body", name: "body", widget: "markdown"}

      - file: "adelaide.md"
        label: "Adelaide"
        name: "adelaide"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Page Type", name: "page", widget: "hidden", default: "fringe"}
          - {label: "Footer", name: "footer", widget: "select", options: ["light", "dark"], default: "light"}
          - {label: "Layout", name: "layout", widget: "string", default: "wide"}
          - {label: "Body", name: "body", widget: "markdown"}

      - file: "perth.md"
        label: "Perth"
        name: "perth"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Page Type", name: "page", widget: "hidden", default: "fringe"}
          - {label: "Footer", name: "footer", widget: "select", options: ["light", "dark"], default: "light"}
          - {label: "Layout", name: "layout", widget: "string", default: "wide"}
          - {label: "Body", name: "body", widget: "markdown"}

      - file: "melbourne.md"
        label: "Melbourne"
        name: "melbourne"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Page Type", name: "page", widget: "hidden", default: "fringe"}
          - {label: "Footer", name: "footer", widget: "select", options: ["light", "dark"], default: "light"}
          - {label: "Layout", name: "layout", widget: "string", default: "wide"}
          - {label: "Body", name: "body", widget: "markdown"}

      - file: "fringe.md"
        label: "Fringe"
        name: "fringe"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Page Type", name: "page", widget: "hidden", default: "fringe"}
          - {label: "Footer", name: "footer", widget: "select", options: ["light", "dark"], default: "light"}
          - {label: "Layout", name: "layout", widget: "string", default: "wide"}
          - {label: "Body", name: "body", widget: "markdown"}

      - file: "kids.md"
        label: "Kids"
        name: "kids"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Page Type", name: "page", widget: "hidden", default: "fringe"}
          - {label: "Footer", name: "footer", widget: "select", options: ["light", "dark"], default: "light"}
          - {label: "Layout", name: "layout", widget: "string", default: "wide"}
          - {label: "Body", name: "body", widget: "markdown"}

      - file: "about-us.md"
        label: "About Us"
        name: "about-us"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Footer", name: "footer", widget: "select", options: ["light", "dark"], default: "light"}
          - {label: "Layout", name: "layout", widget: "string", default: "wide"}
          - {label: "Body", name: "body", widget: "markdown"}

      - file: "thanks.md"
        label: "Thanks"
        name: "thanks"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Footer", name: "footer", widget: "select", options: ["light", "dark"], default: "light"}
          - {label: "Layout", name: "layout", widget: "string", default: "wide"}
          - {label: "Body", name: "body", widget: "markdown"}

      - file: "toast-live.md"
        label: "Toast Live"
        name: "toast-live"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Footer", name: "footer", widget: "select", options: ["light", "dark"], default: "light"}
          - {label: "Layout", name: "layout", widget: "string", default: "wide"}
          - {label: "Body", name: "body", widget: "markdown"}

      - file: "whats-on.md"
        label: "Whats On"
        name: "whats-on"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Footer", name: "footer", widget: "select", options: ["light", "dark"], default: "light"}
          - {label: "Layout", name: "layout", widget: "string", default: "wide"}
          - {label: "Body", name: "body", widget: "markdown"}
